// <auto-generated />
using System;
using Dragza.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dragza.Application.Migrations
{
    [DbContext(typeof(DragzaContext))]
    [Migration("20251111114220_addcarts")]
    partial class addcarts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dragza.Domain.Models.ActiveIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMeltable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActiveIngredient", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__BalanceA__3214EC07AEDCCED6");

                    b.HasIndex(new[] { "UserId" }, "IX_BalanceAccounts_UserId");

                    b.ToTable("BalanceAccounts");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("BalanceAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__BalanceT__3214EC07E9118AE8");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex(new[] { "BalanceAccountId" }, "IX_BalanceTransactions_BalanceAccountId");

                    b.HasIndex(new[] { "OrderId" }, "IX_BalanceTransactions_OrderId");

                    b.ToTable("BalanceTransactions");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BestSellerProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalQuantitySold")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BestSellerProduct", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Dragza.Domain.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MainCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pref")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GovernateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Area");

                    b.HasIndex("GovernateId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaximumDiscountAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("maximum_discount_amount");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("minimum_order_amount");

                    b.Property<int?>("PerUserLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("per_user_limit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("usage_limit");

                    b.HasKey("Id")
                        .HasName("PK__coupons__3213E83FC3864A76");

                    b.HasIndex(new[] { "IsActive", "StartDate", "EndDate" }, "IX_coupons_active");

                    b.HasIndex(new[] { "Code" }, "IX_coupons_code");

                    b.HasIndex(new[] { "Code" }, "UQ__coupons__357D4CF970C4BAC3")
                        .IsUnique();

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.CouponApplicability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("ApplicableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("applicable_id");

                    b.Property<string>("ApplicableType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("applicable_type");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__coupon_a__3213E83FECA136AB");

                    b.HasIndex(new[] { "CouponId", "ApplicableType", "ApplicableId" }, "IX_coupon_applicability");

                    b.ToTable("coupon_applicability", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.CouponUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coupon_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discount_amount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__coupon_u__3213E83F8C342324");

                    b.HasIndex(new[] { "CouponId" }, "IX_coupon_usages_coupon");

                    b.HasIndex(new[] { "OrderId" }, "IX_coupon_usages_order");

                    b.HasIndex(new[] { "UserId" }, "IX_coupon_usages_user");

                    b.HasIndex(new[] { "CouponId", "OrderId" }, "UQ_CouponOrder")
                        .IsUnique();

                    b.ToTable("coupon_usages", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Destrict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Destrict", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Governate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Governate", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("InvoiceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PharmacyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex(new[] { "OrderId" }, "IX_Invoices_OrderId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.InvoiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__InvoiceT__3214EC07A00F4181");

                    b.ToTable("InvoiceTypes");
                });

            modelBuilder.Entity("Dragza.Domain.Models.MainCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainCategory", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("CashPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreditAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CreditUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("InventoryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PharmacyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("CreditAccountId");

                    b.HasIndex("InventoryUserId");

                    b.HasIndex(new[] { "PharmacyUserId" }, "IX_Orders_PharmacyUserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPriceId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.PharmacyDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommercialRegisteryAttach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommercialRegisteryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DemoAgentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandLineNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalIdAttach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnersgipAttach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PharmacyLicenseAttach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PharmacyLicenseNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PurchasingManager")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxationCardAttach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxationCardNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PurchasingManager");

                    b.HasIndex("UserId");

                    b.ToTable("PharmacyDetails");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveIngerdientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MainCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Preef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ActiveIngerdientId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount Rate");

                    b.Property<Guid>("InventoryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MainCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SalesPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InventoryUserId");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrice", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lat");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdminApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("InventoryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PharmacyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReturnOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Statuse")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalReturnValue")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryUserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PharmacyUserId");

                    b.ToTable("ReturnOrder", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ReturnReason", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OtherReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityReturned")
                        .HasColumnType("int");

                    b.Property<Guid>("ReasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReturnOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPriceId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("ReturnOrderId");

                    b.ToTable("ReturnedItem", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BussinesName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPharmacy")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinOrder")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("NomalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SubAreaId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Dragza.Domain.Models.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceAccount", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "User")
                        .WithMany("BalanceAccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BalanceAccounts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceTransaction", b =>
                {
                    b.HasOne("Dragza.Domain.Models.BalanceAccount", "BalanceAccount")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("BalanceAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_BalanceTransactions_BalanceAccounts");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_BalanceTransactions_Orders");

                    b.HasOne("Dragza.Domain.Models.BalanceTransaction", "RelatedTransaction")
                        .WithMany("InverseRelatedTransaction")
                        .HasForeignKey("RelatedTransactionId")
                        .HasConstraintName("FK_BalanceTransactions_RelatedTransactions");

                    b.Navigation("BalanceAccount");

                    b.Navigation("Order");

                    b.Navigation("RelatedTransaction");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BestSellerProduct", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Product", "Product")
                        .WithMany("BestSellerProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_BestSellerProduct_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dragza.Domain.Models.CartItem", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragza.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Category", b =>
                {
                    b.HasOne("Dragza.Domain.Models.MainCategory", "MainCategory")
                        .WithMany("Categories")
                        .HasForeignKey("MainCategoryId")
                        .HasConstraintName("FK_Category_MainCategory");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Dragza.Domain.Models.City", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Governate", "Governate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernateId")
                        .IsRequired()
                        .HasConstraintName("FK_City_Governate");

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("Dragza.Domain.Models.CouponApplicability", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Coupon", "Coupon")
                        .WithMany("CouponApplicabilities")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__coupon_ap__coupo__6166761E");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Dragza.Domain.Models.CouponUsage", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Coupon", "Coupon")
                        .WithMany("CouponUsages")
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK__coupon_us__coupo__690797E6");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("CouponUsages")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_coupon_usages_Order");

                    b.HasOne("Dragza.Domain.Models.User", "User")
                        .WithMany("CouponUsages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_coupon_usages_User");

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Destrict", b =>
                {
                    b.HasOne("Dragza.Domain.Models.City", "City")
                        .WithMany("Destricts")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK_Destrict_City");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Governate", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Region", "Region")
                        .WithMany("Governates")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("FK_Governate_Region");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Invoice", b =>
                {
                    b.HasOne("Dragza.Domain.Models.InvoiceType", "InvoiceType")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_InvoiceTypes");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Order");

                    b.Navigation("InvoiceType");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Order", b =>
                {
                    b.HasOne("Dragza.Domain.Models.BalanceAccount", "CreditAccount")
                        .WithMany("Orders")
                        .HasForeignKey("CreditAccountId")
                        .HasConstraintName("FK_Order_BalanceAccounts");

                    b.HasOne("Dragza.Domain.Models.User", "InventoryUser")
                        .WithMany("OrderInventoryUsers")
                        .HasForeignKey("InventoryUserId")
                        .HasConstraintName("FK_Order_User1");

                    b.HasOne("Dragza.Domain.Models.User", "PharmacyUser")
                        .WithMany("OrderPharmacyUsers")
                        .HasForeignKey("PharmacyUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("CreditAccount");

                    b.Navigation("InventoryUser");

                    b.Navigation("PharmacyUser");
                });

            modelBuilder.Entity("Dragza.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "Inventory")
                        .WithMany("OrderItems")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("FK_OrderItem_User");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Order");

                    b.HasOne("Dragza.Domain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_Product");

                    b.HasOne("Dragza.Domain.Models.ProductPrice", "ProductPrice")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductPriceId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_ProductPrice");

                    b.Navigation("Inventory");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductPrice");
                });

            modelBuilder.Entity("Dragza.Domain.Models.PharmacyDetail", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "PurchasingManagerNavigation")
                        .WithMany("PharmacyDetailPurchasingManagerNavigations")
                        .HasForeignKey("PurchasingManager")
                        .HasConstraintName("FK_PharmacyDetails_User1");

                    b.HasOne("Dragza.Domain.Models.User", "User")
                        .WithMany("PharmacyDetailUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PharmacyDetails_User");

                    b.Navigation("PurchasingManagerNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Product", b =>
                {
                    b.HasOne("Dragza.Domain.Models.ActiveIngredient", "ActiveIngerdient")
                        .WithMany("Products")
                        .HasForeignKey("ActiveIngerdientId")
                        .HasConstraintName("FK_Product_ActiveIngredient");

                    b.HasOne("Dragza.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("Dragza.Domain.Models.MainCategory", "MainCategory")
                        .WithMany("Products")
                        .HasForeignKey("MainCategoryId")
                        .HasConstraintName("FK_Product_MainCategory");

                    b.Navigation("ActiveIngerdient");

                    b.Navigation("Category");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ProductPrice", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Category", "Category")
                        .WithMany("ProductPrices")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_ProductPrice_Category");

                    b.HasOne("Dragza.Domain.Models.User", "InventoryUser")
                        .WithMany("ProductPrices")
                        .HasForeignKey("InventoryUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductPrice_User");

                    b.HasOne("Dragza.Domain.Models.MainCategory", "MainCategory")
                        .WithMany("ProductPrices")
                        .HasForeignKey("MainCategoryId")
                        .HasConstraintName("FK_ProductPrice_MainCategory");

                    b.HasOne("Dragza.Domain.Models.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductPrice_Product");

                    b.Navigation("Category");

                    b.Navigation("InventoryUser");

                    b.Navigation("MainCategory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnOrder", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "InventoryUser")
                        .WithMany("ReturnOrderInventoryUsers")
                        .HasForeignKey("InventoryUserId")
                        .HasConstraintName("FK_ReturnOrder_User1");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("ReturnOrders")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnOrder_Order");

                    b.HasOne("Dragza.Domain.Models.User", "PharmacyUser")
                        .WithMany("ReturnOrderPharmacyUsers")
                        .HasForeignKey("PharmacyUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnOrder_User");

                    b.Navigation("InventoryUser");

                    b.Navigation("Order");

                    b.Navigation("PharmacyUser");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnedItem", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "Inventory")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("FK_ReturnedItem_User");

                    b.HasOne("Dragza.Domain.Models.Order", "Order")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnedItem_Order");

                    b.HasOne("Dragza.Domain.Models.Product", "Product")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnedItem_Product");

                    b.HasOne("Dragza.Domain.Models.ProductPrice", "ProductPrice")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("ProductPriceId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnedItem_ProductPrice");

                    b.HasOne("Dragza.Domain.Models.ReturnReason", "Reason")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("ReasonId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnedItem_ReturnReason");

                    b.HasOne("Dragza.Domain.Models.ReturnOrder", "ReturnOrder")
                        .WithMany("ReturnedItems")
                        .HasForeignKey("ReturnOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnedItem_ReturnOrder");

                    b.Navigation("Inventory");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductPrice");

                    b.Navigation("Reason");

                    b.Navigation("ReturnOrder");
                });

            modelBuilder.Entity("Dragza.Domain.Models.User", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Region", "Region")
                        .WithMany("Users")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("FK_User_Region");

                    b.HasOne("Dragza.Domain.Models.Governate", "SubArea")
                        .WithMany("Users")
                        .HasForeignKey("SubAreaId")
                        .HasConstraintName("FK_User_Governate");

                    b.Navigation("Region");

                    b.Navigation("SubArea");
                });

            modelBuilder.Entity("Dragza.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Dragza.Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("Dragza.Domain.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragza.Domain.Models.UserToken", b =>
                {
                    b.HasOne("Dragza.Domain.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ActiveIngredient", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceAccount", b =>
                {
                    b.Navigation("BalanceTransactions");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Dragza.Domain.Models.BalanceTransaction", b =>
                {
                    b.Navigation("InverseRelatedTransaction");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Category", b =>
                {
                    b.Navigation("ProductPrices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Dragza.Domain.Models.City", b =>
                {
                    b.Navigation("Destricts");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Coupon", b =>
                {
                    b.Navigation("CouponApplicabilities");

                    b.Navigation("CouponUsages");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Governate", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dragza.Domain.Models.InvoiceType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Dragza.Domain.Models.MainCategory", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ProductPrices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Order", b =>
                {
                    b.Navigation("BalanceTransactions");

                    b.Navigation("CouponUsages");

                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");

                    b.Navigation("ReturnOrders");

                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Product", b =>
                {
                    b.Navigation("BestSellerProducts");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductPrices");

                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ProductPrice", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Region", b =>
                {
                    b.Navigation("Governates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnOrder", b =>
                {
                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.ReturnReason", b =>
                {
                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Dragza.Domain.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dragza.Domain.Models.User", b =>
                {
                    b.Navigation("BalanceAccounts");

                    b.Navigation("CouponUsages");

                    b.Navigation("OrderInventoryUsers");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderPharmacyUsers");

                    b.Navigation("PharmacyDetailPurchasingManagerNavigations");

                    b.Navigation("PharmacyDetailUsers");

                    b.Navigation("ProductPrices");

                    b.Navigation("ReturnOrderInventoryUsers");

                    b.Navigation("ReturnOrderPharmacyUsers");

                    b.Navigation("ReturnedItems");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
